#!/usr/bin/env bash
# =============================================================================
# build-portfolio.sh - mirror the "Videos to use" folder into the V3 Finder.
#
# WHAT IT DOES
#   - Each SUBFOLDER of the source becomes a folder/section in the Finder
#     (e.g. "AI - UGC", "Animated", "B-Roll").
#   - Each video inside a subfolder becomes a clip in that folder.
#   - For every clip it makes a ~30s web preview (assets/work/<slug>.mp4) and a
#     poster still (assets/work/<slug>.jpg).
#   - Rewrites  assets/work/folders.js  = the data the Finder reads.
#
# HOW TO USE (no coding needed)
#   1. Organise "Videos to use" into subfolders. The subfolder names are the
#      section names shown on the site. Filenames become the clip titles.
#   2. Run:  bash v3/tools/build-portfolio.sh
#      (or point elsewhere:  bash v3/tools/build-portfolio.sh "/path/to/folder")
#   3. Refresh the site. Folders + clips update themselves.
#
# Plays a 30s preview per clip (keeps it light). Swap to full clips / R2 links
# later by changing the -t value below or editing folders.js.
# Needs ffmpeg.
# =============================================================================
set -uo pipefail   # NOT -e: a flaky encode on one big file must not kill the run

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
SRC="${1:-$ROOT/Videos to use}"
OUT="$HERE/../assets/work"
[ -d "$SRC" ] || { echo "Source folder not found: $SRC" >&2; exit 1; }

mkdir -p "$OUT"
rm -f "$OUT"/*.mp4 "$OUT"/*.jpg "$OUT"/folders.js

# Big source files occasionally fail to encode on the first pass; retry a few times.
# NOTE: -nostdin + </dev/null are essential here. ffmpeg reads stdin by default,
# and inside the `while read` loop below it would otherwise eat the file-list
# stream and break every other iteration.
encode() { # $1 src  $2 out
  local n=0
  while [ "$n" -lt 3 ]; do
    if ffmpeg -nostdin -y -ss 1 -t 30 -i "$1" -vf "scale=720:-2" -c:v libx264 -preset veryfast -crf 28 \
        -threads 3 -c:a aac -b:a 96k -movflags +faststart -pix_fmt yuv420p "$2" >/dev/null 2>&1 </dev/null; then
      return 0
    fi
    n=$((n + 1)); sleep 1
  done
  return 1
}
poster() { # $1 src  $2 timestamp  $3 out
  local n=0
  while [ "$n" -lt 3 ]; do
    if ffmpeg -nostdin -y -ss "$2" -i "$1" -frames:v 1 -vf "scale=360:-2" -q:v 4 "$3" >/dev/null 2>&1 </dev/null; then
      return 0
    fi
    n=$((n + 1)); sleep 1
  done
  return 1
}

accents=(coral violet amber pink)
fi=0
folders_js=""

while IFS= read -r -d '' D; do
  fname="$(basename "$D")"
  fslug="$(printf '%s' "$fname" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]\{1,\}/-/g; s/^-//; s/-$//')"
  accent="${accents[$((fi % ${#accents[@]}))]}"
  vids=""
  vi=0
  while IFS= read -r -d '' V; do
    vi=$((vi + 1))
    base="$(basename "$V")"; name="${base%.*}"
    slug="${fslug}-$(printf '%02d' "$vi")"
    if ! encode "$V" "$OUT/$slug.mp4"; then
      echo "  ! skipped (encode failed after retries): $base"
      continue
    fi
    dur="$(ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 "$V" 2>/dev/null || echo 6)"
    pts="$(awk -v d="$dur" 'BEGIN{t=d*0.35; if(t<1)t=1; printf "%.2f", t}')"
    poster "$V" "$pts" "$OUT/$slug.jpg" || echo "  ~ poster failed (card will show a gradient): $base"
    odur="$(ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 "$OUT/$slug.mp4" 2>/dev/null || echo 0)"
    label="$(awk -v d="$odur" 'BEGIN{m=int(d/60); s=int(d)%60; printf "%d:%02d", m, s}')"
    esc="$(printf '%s' "$name" | sed 's/\\/\\\\/g; s/"/\\"/g')"
    vids="$vids      { title: \"$esc\", duration: \"$label\", src: \"assets/work/$slug.mp4\", poster: \"assets/work/$slug.jpg\" },\n"
    echo "  [$fname] $slug  <-  $base"
  done < <(find "$D" -maxdepth 1 -type f \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' -o -iname '*.webm' \) -print0 | sort -z)

  if [ -n "$vids" ]; then
    fesc="$(printf '%s' "$fname" | sed 's/\\/\\\\/g; s/"/\\"/g')"
    folders_js="$folders_js  {\n    name: \"$fesc\",\n    accent: \"$accent\",\n    videos: [\n$vids    ]\n  },\n"
    fi=$((fi + 1))
  fi
done < <(find "$SRC" -mindepth 1 -maxdepth 1 -type d -print0 | sort -z)

{
  echo "/* AUTO-GENERATED by v3/tools/build-portfolio.sh - do not hand-edit."
  echo "   Mirrors the \"Videos to use\" folder: each subfolder = a Finder folder,"
  echo "   each video = a clip. Re-run after adding clips or folders. */"
  echo "window.LIKELYFAD_FOLDERS = ["
  printf "%b" "$folders_js"
  echo "];"
} > "$OUT/folders.js"

echo ""
echo "Done: $fi folders written to assets/work/folders.js"
