#!/usr/bin/env bash
# =============================================================================
# build-wall.sh - turn a folder of videos into the V3 showcase wall.
#
# WHAT IT DOES
#   - Looks at every video in a source folder (.mp4 .mov .m4v .webm)
#   - Pulls ONE representative still frame from each (about a third of the way in)
#   - Saves each as a small web image in  v3/assets/wall/NN.jpg
#   - Rewrites  v3/assets/wall/manifest.js  = the list the website reads
#
# HOW TO USE  (you do NOT need to be a coder)
#   1. Drop your clips into the source folder (default: "Videos to use/AI - UGC").
#   2. Run this once:
#        bash v3/tools/build-wall.sh
#      ...or point it at any folder:
#        bash v3/tools/build-wall.sh "/full/path/to/your/folder"
#   3. Refresh the site. The wall now shows one tile per clip, and the count
#      updates itself. Add more clips later and just run it again.
#
# Needs ffmpeg (already installed on this machine).
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"                       # project root
SRC="${1:-$ROOT/Videos to use/AI - UGC}"               # default source folder
OUT="$HERE/../assets/wall"                              # where tiles + manifest go

if [ ! -d "$SRC" ]; then
  echo "Source folder not found: $SRC" >&2
  exit 1
fi

mkdir -p "$OUT"
rm -f "$OUT"/*.jpg

i=0
items=""
while IFS= read -r -d '' f; do
  i=$((i+1))
  num=$(printf "%02d" "$i")
  # Grab a frame ~35% into the clip (skips intros / title cards).
  dur=$(ffprobe -v error -show_entries format=duration -of default=nk=1:nw=1 "$f" 2>/dev/null || echo 6)
  ts=$(awk -v d="$dur" 'BEGIN{ t=d*0.35; if(t<1)t=1; printf "%.2f", t }')
  ffmpeg -y -ss "$ts" -i "$f" -frames:v 1 -vf "scale=360:-2" -q:v 4 "$OUT/$num.jpg" >/dev/null 2>&1
  base=$(basename "$f"); name="${base%.*}"
  esc=$(printf '%s' "$name" | sed 's/\\/\\\\/g; s/"/\\"/g')
  items="$items  { src: \"assets/wall/$num.jpg\", label: \"$esc\" },\n"
  echo "  tile $num  <-  $base"
done < <(find "$SRC" -maxdepth 1 -type f \( -iname '*.mp4' -o -iname '*.mov' -o -iname '*.m4v' -o -iname '*.webm' \) -print0 | sort -z)

{
  echo "/* AUTO-GENERATED by v3/tools/build-wall.sh - do not hand-edit."
  echo "   Re-run the script after adding clips to the source folder. */"
  echo "window.LIKELYFAD_WALL = ["
  printf "%b" "$items"
  echo "];"
} > "$OUT/manifest.js"

echo ""
echo "Done: $i tiles + manifest written to v3/assets/wall/"
